### ISSUE TITLE
Use of openssl_random_pseudo_bytes might not be secure

### ISSUE THREAD

**Issue by relaxnow** [zendframework/zend-math#15]
Depending on your PHP and OpenSSL configuration. See also: https://github.com/paragonie/random_compat/issues/96

**Comment by ezimuel** [comment]
@relaxnow yes, we know the PHP bug [#70014](https://bugs.php.net/bug.php?id=70014) related to OpenSSL versions. I'm working on a fix to support PHP 7 functions if available or paragonie/random_compat.

**Comment by ezimuel** [comment]
@relaxnow I just sent the PR #16 to remove the usage of OpenSSL.
