### ISSUE TITLE
RandomLib not found

### ISSUE THREAD

**Issue by flowl** [zendframework/zend-math#35]
The namespace with its classes under `RandomLib` is not available, it is not defined in composer.json and not in any file.

This whole project does not work when dependencies are missing.

See https://github.com/zendframework/zend-math/blob/master/src/Rand.php#L12

`use RandomLib;`

**Comment by flowl** [comment]
Solution could be to add the dependency:

    $ composer require ircmaxell/random-lib

**Comment by ezimuel** [comment]
@flowl we used [paragonie/random_compat](https://github.com/paragonie/random_compat) instead of [ircmaxell/RandomLib](https://github.com/ircmaxell/RandomLib) since zend-math 3.0.0.
The use of RandomLib in the code was a old reference. Thanks for reporting this!
